#!/usr/bin/env bash
#script that displays, The content of the current directory.In a list format (one item per line).Where only the part of the name after the first dash (-) is displayed (refer to the example for clarity).
for FILE in *; do
 if [[ "$FILE" == *_* ]]; then
  echo "${FILE#*_}"
 else
  continue
 fi
done
