#!/usr/bin/env bash
#script that displays, The content of the current directory.In a list format (one item per line).Where only the part of the name after the first dash (-) is displayed (refer to the example for clarity).
for FILENAME in *; do
 if [[ "$FILENAME" == *_* ]]; then
  echo "${FILENAME*-}"
else
 echo "$FILENAME"
fi
done
